# ===================================================================================================
#                                           Neptune Carbon
#
#                                        Do not redistribute.
# ===================================================================================================
databaseUrl: 'mongodb+srv://admin:admin@cluster0.nvkveq7.mongodb.net/?retryWrites=true&w=majority'
preset: 'invaded'
allowedServersBanned:
  - hub
  - Lobby

motd:
  - '&b&lCrest Network &7[1.8-1.18] &3(Dev Proxy)'
  - '&3&lUNDER DEVELOPMENT!'

whitelisted: false