# ===================================================================================================
#                                           Neptune Carbon
#
#                                        Do not redistribute.
# ===================================================================================================
databaseUrl: 'mongodb+srv://admin:admin@cluster0.nvkveq7.mongodb.net/?retryWrites=true&w=majority'
preset: 'outerworlds'
serverName: 'testing'
license-key: 'NOT_SET'

chat:
  muted: false
  format: '%prefix%%player%&7: &f%msg%'

ranks:
  defaultRankName: 'default'
  defaultRankPermissions:
    - 'rank.default'
    - 'default'

# UNCOMMENT BTW
#banAppealLink: 'appeal link here'
#blacklistAppealLink: 'yeah'
#unbanPurchaseLink: 'idfk'
#unblacklistPurchaseLink: 'k'